### ISSUE TITLE
The original files available?

### ISSUE THREAD

**Issue by deep-diver** [nekocode/codelabs-hugo-theme#1]
I am having a hard time to deal with the minified files to add custom look, and I decided to contact you @nekocode 

Can you please provide the original (before being minified) source codes?

Thank you

**Comment by nekocode** [comment]
You can find them here: https://github.com/googlecodelabs/tools

**Comment by deep-diver** [comment]
@nekocode 

Thanks for the response! 
It seems like it is non-trivial to migrate current theme of `googlecodelabs` into `codelabs-hugo-theme` for me.
so, I am just trying to override the existing scripts and styles by adding new files.

One question.
- When executing `./build_docs.sh`, it does not copy my custom files into `docs` folder. Do you know how?

**Comment by nekocode** [comment]
You need to import the script or style files in the way specified by Hugo. You can read the documentation at https://gohugo.io/documentation/

**Comment by deep-diver** [comment]
Thanks! I just made that work.
I have override the javascript and css to make it look as smilier as possible to Googlecodelabs.

<img width="1201" alt="Screen_Shot_2021-09-02_at_3 00 16_PM" src="https://user-images.githubusercontent.com/26025527/131793557-8ca1a2a6-6161-45f2-b07d-f12d02467d98.png">
